version: "3.9"
services:
  postgres:
    container_name: shop_postgres
    image: postgres:13.8
    environment:
      POSTGRES_DB: 'shop_dev'
      POSTGRES_USER: 'shop_dev'
      POSTGRES_PASSWORD: 'pass'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop_dev -d shop_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  pgadmin:
    container_name: shop_pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "shop_dev@example.com"
      PGADMIN_DEFAULT_PASSWORD: "shop_dev"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
  web:
    container_name: shop_dev
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    ports:
      - "80:80"
    command: honcho start
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: "shop_dev"
      POSTGRES_USER: "shop_dev"
      POSTGRES_PASSWORD: "pass"
      DB_HOST: postgres
